exec-once = /nix/store/8kih8alkk4qzgjchg5501r1c3a8a71aw-dbus-1.16.2/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
$menu=rofi -show drun
$terminal=kitty
bind=SUPER, T, exec, $terminal
bind=SUPER, R, exec, $menu
bind=SUPER, E, exec, nautilus
bind=SUPER, Q, killactive
bind=SUPER, F, fullscreen
bind=SUPER SHIFT, E, exit
bind=SUPER, 1, workspace, 1
bind=SUPER, 2, workspace, 2
bind=SUPER, 3, workspace, 3
bind=SUPER SHIFT, 1, movetoworkspace, 1
bind=SUPER SHIFT, 2, movetoworkspace, 2
bind=SUPER SHIFT, 3, movetoworkspace, 3

exec-once=waybar
exec-once=mako
exec-once=hyprpaper
exec-once=nm-applet
exec-once=/run/current-system/sw/libexec/polkit-gnome-authentication-agent-1

input {
  touchpad {
    natural_scroll=true
  }
  follow_mouse=1
  kb_layout=us,ru
  kb_options=grp:win_space_toggle
}
